# Generated by Django 3.2.7 on 2021-09-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('options', models.CharField(blank=True, max_length=100, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.survey')),
            ],
        ),
    ]
