# Generated by Django 3.2.7 on 2021-09-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_auto_20210906_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
