# Generated by Django 3.2.7 on 2021-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
