# Generated by Django 3.2.7 on 2021-09-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_question_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_report', models.JSONField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.survey')),
            ],
        ),
    ]
